services:
  ## google APIS base url
  - name: googleMapBaseUrl
    url: https://addressvalidation.googleapis.com
    timeout: HIGH

  - name: geoJsonBaseUrl
    url: https://api.met.no/weatherapi/locationforecast
    timeout: HIGH