
#remote call timeout for medium timeouts
remote_call_timeout: 2000
#dial timeout
dial_timeout: 1000
#keep alive timeout
keep_alive_timeout: 1000

##configurations for low/less timeouts
#remote call timeout for low
remote_call_timeout_low: 1000
#dial timeout for low
dial_timeout_low: 1000
#keep alive timeout
keep_alive_timeout_low: 1000

##configurations for high/longer timeouts
#remote call timeout for high
remote_call_timeout_high: 600000
#dial timeout for high
dial_timeout_high: 100000
#keep alive timeout
keep_alive_timeout_high: 100000


cron_job_time_interval: "*/1 * * * *"

update_interval: 1 min
